name: CI/CD Pipeline
run-name: Lint, Format, Generate JSDocs
on:
  push:

permissions:
  contents: write

jobs:
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: npm run lint

  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Check if Prettier could format code
        run: npx prettier --check --no-config .

  jsdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build JSDOCS
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./JSDOCs
          config_file: .jsdoc.conf.json
          template: minami
      - name: Commit JSDOCS
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: "Generated JSDocs"
          add: "JSDOCs/*"
