name: Generate JSDOCS
run-name: Action by @${{ github.actor }}
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  jsdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build JSDOCS
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          recurse: true
          output_dir: ./JSDOCs
          config_file: .jsdoc.conf.json
          template: minami
      - name: Commit JSDOCS
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: noreply@github.com
          message: "Generated JSDocs"
          add: "JSDOCs/*"
